# Genomic Best Linear Unbiased Prediction (GBLUP) {#gblup}
Die Methode GBLUP verwendet genomische Verwandtschaftsbeziehungen zur Schätzung des genetischen Potentials von Individuen. Die genomische Verwandtschaft wird aufgrund von DNA-Informationen geschätzt. Die genomische Verwandtschaftsmatrix $G$ definiert die Kovarianz zwischen Individuen aufgrund von Ähnlichkeiten auf dem Niveau der genomischen Information. Diese Definition der Kovarianz steht im Gegensatz zur Kovarianz aufgrund der erwarteten Ähnlichkeit aufgrund von Pedigrees in der traditionellen Verwandtschaftsmatrix $A$. 


## DNA Markers
Die Verfügbarkeit von Markerkarten in genügender Dichte verteilt über das ganze Genom, ermöglicht die Schätzung des genetischen Potentials von Individuen basierend auf der beobachteten Markerinformation. Das aktuell am weitesten verbreitete Markermodell wird als `r r6objTableAbbrev$add_abbrev(psAbbrev = "SNP", psMeaning = "Single Nucleotide Polymorphism")` bezeichnet. Bei den SNPs handelt es sich um Positionen im Genom, an welchen Unterschiede zwischen Individuen einer Population bei einer einzelnen DNA-Base auftreten. Nehmen wir an, dass Genorte (QTL), welche wichtig sind für die Expression von interessanten phänotypischen Eigenschaften, sich in der Nähe von beobachteten SNPs befinden, können wir aufgrund von Kopplungsungleichgewichten zwischen SNPs und QTL eine statistische Beziehung zwischen phänotypischen Werten und SNP-Genotypen modellieren.

Für die Schätzung der SNP-Effekte auf phänotypische Ausprägungen stehen verschiedene statistische Verfahren zur Verfügung. Als einfachste Methode können wir die Regression auf einzelne SNP-Marker bezeichnen. Das Problem der Single-Marker Regression liegt in der im Vergleich zur Anzahl der Beobachtungen sehr grossen Anzahl an SNP-Markern. Eine Lösung dieses Problems besteht darin, dass die SNP-Effekte im linearen Modell als zufällige Effekte aufgefasst werden. Dadurch wird das einfache lineare Regressionsmodell in ein lineares gemischtes Modell verwandelt. Aus der traditionellen Zuchtwertschätzung ([@Hofer1990] und [@vonRohr2016]) kennen wir die Mischmodellgleichungen, welche uns Schätzwerte für fixe und zufällige Effekte mit BLUE- und BLUP-Eigenschaften liefern. Bei diesem Verfahren werden aber allen SNPs der gleiche Varianzanteil zugesprochen. Die totale genetische Varianz wird somit auf alle SNPs gleichmässig aufgeteilt. Bayes'sche Methoden, wie sie in Kapitel \@ref(bayes) beschrieben sind, erlauben es verschiedenen genomischen Regionen verschiedene Varianzanteile zuzuordnen.


## Markerinformationen in BLUP-Verfahren
Parameterschätzverfahren, welche zu Schätzungen für fixe Effekte mit `r r6objTableAbbrev$add_abbrev(psAbbrev = "BLUE", psMeaning = "Best Linear Unbiased Estimation")`-Eigenschaften und zu Vorhersagen von zufälligen Effekten mit `r r6objTableAbbrev$add_abbrev(psAbbrev = "BLUP", psMeaning = "Best Linear Unbiased Prediction")`-Eigenschaften führen werden hier kurz als __BLUP-Verfahren__ bezeichnet. Die traditionelle Zuchtwertschätzung basiert auf Pedigreeinformationen zur Schätzung der Covarianz zwischen zufälligen Effekten (Zuchtwerten) von verwandten Tieren. Die Covarianz kann aber auch aufgrund von Markerinformation geschätzt werden. Die aufgrund von SNPs erstellte Matrix wird als `r r6objTableAbbrev$add_abbrev(psAbbrev = "GRM", psMeaning = "Genomic Relationship Matrix")` bezeichnet. 

Wir besprechen hier zwei verschiedene Ansätze

1. `r r6objTableAbbrev$add_abbrev(psAbbrev = "RR", psMeaning = "Ridge Regression")`-BLUP
2. `r r6objTableAbbrev$add_abbrev(psAbbrev = "GBLUP", psMeaning = "Genomic BLUP")`

### Ridge Regression (RR) BLUP
Diese Methode wurde von [@MHG2001] und [@HFD2007] untersucht. Dabei haben die Autoren das folgende Modell angenommen.

\begin{equation}
y = 1_n\mu + Wq + e
\label{eq:RRBlupModel}
\end{equation}

\begin{tabular}{lll}
wobei  &         & \\
       &  $y$    &  Vektor der Länge $n$ mit Beobachtungen \\
       &  $\mu$  &  allgemeines Mittel \\
       &  $q$    &  Vektor der Länge $m$ mit zufälligen SNP-Effekten\\
       &  $W$    &  Matrix der Dimension $n\times m$, welche SNP-Genotypen codiert\\
       &  $e$    &  Vektor der Länge $n$ mit zufälligen Resteffekten
\end{tabular}

Die Genotypen an jedem SNP-Locus in Matrix $W$ werden mit $0$, $1$ und $2$ codiert. Diese Codes repräsentieren die Anzahl an SNP-Allelen mit positiver Wirkung. Die SNP-Effekte werden als zufällig betrachtet. Das Modell in (\ref{eq:RRBlupModel}) ist also ein gemischtes lineares Modell. Die unbekannten Parameter werden mit Hilfe von Mischmodellgleichungen geschätzt. Der geschätzte genomische Zuchtwert entspricht der Summe der SNP-Effekte über alle SNP-Loci. Die durch die SNP-Effekte erklärte Varianz ist gleich $WW^T\sigma_q^2$. Die Varianz der Resteffekte wird als $I\sigma_e^2$ angenommen. Somit entspricht die Covarianz zwischen Beobachtungen $WW^T\sigma_q^2 + I\sigma_e^2$. In RR-BLUP wird die Varianz an allen SNPs als konstant angenommen. 

### Genomic BLUP (GBLUP)
Die zweite Methode, welche genomische Information berücksichtigt verwendet die genomische Verwandtschaftsmatrix $G$ anstelle der additiv genetischen Verwandtschaftsmatrix $A$ in einem gemischten linearen Modell. Dieser Ansatz wird als __gBLUP__ bezeichnet. Das Modell zur Umsetzung von gBLUP lautet

\begin{equation}
y = Xb + Zg + e
\label{eq:GblupModel}
\end{equation}

\begin{tabular}{lll}
wobei  &         & \\
       & $y$     & Vektor der Länge $n$ mit Beobachtungen \\
       & $b$     & Vektor der Länge $r$ mit fixen Effekten \\
       & $X$     & Inzidenzmatrix zur Verknüpfung von $b$ und $y$ \\
       & $g$     & Vektor der Länge $t$ mit zufälligen genetischen Effekten \\
       & $Z$     & Inzidenzmatrix zur Verknüpfung von $g$ und $y$ \\
       & $e$     & Vektor der Länge $n$ mit zufälligen Resteffekten
\end{tabular}

Der Vektor $g$ enthält zufällige genetische Effekte für alle Tiere, welche typisiert sind. Diese Tiere können Beobachtungen aufweisen oder nicht. Die Tiere mit Beobachtungen und Typisierungsergebnisse werden allgemein als Trainings- oder Referenzpopulation bezeichnet. Die Tiere ohne phänotypische Beobachtung mit Typisierungsergebnissen bilden das Testset, für welche die genomischen Zuchtwerte geschätzt werden sollen. Die Varianz $var(g) = G * \sigma_g^2$ wobei $G$ der genomischen Verwandtschaftsmatrix entspricht. Die zufälligen Resteffekte werden als unabhängig angenommen mit der Covarianzmatrix $var(e) = I*\sigma_e^2$.  

GBLUP hat drei wichtige Vorteile im Vergleich zu RR-BLUP.

1. Die Dimension der genetischen Effekte in GBLUP beträgt $n\times n$, wobei $n$ die Anzahl Tiere sind. In RR-BLUP beträgt diese Dimension $m\times m$, wobei $m$ der Anzahl an SNP-Markern entspricht. Somit ist GBLUP effizienter im Hinblick auf Rechenresourcen.
2. Die Genauigkeiten der genomischen Zuchtwerte können bei GBLUP analog zu den Genauigkeiten der Zuchtwerte im BLUP-Tiermodell berechnet werden.
3. GBLUP kann mit Pedigree-basierten Informationen zu den sogenannten __single step__ Verfahren kombiniert werden [@MLA2009]. 


## Genomische Verwandtschaftsmatrix (GRM)
Die Covarianz zwischen den gentischen Effekten $g$ im Modell (\ref{eq:GblupModel}) wird über die genomische Verwandtschaftsmatrix $G$ ausgedrückt. Analog zum BLUP-Tiermodell, soll die Covarianz der genetischen Effekte als Produkt der genomischen Verwandtschaftsmatrix $G$ mal die Varianzkomponente $\sigma_g^2$ dargestellt werden. 

### Herleitung der GRM
Als erstes stellt sich die Frage, wie wir die genetischen Effekte $g$ überhaupt definieren sollen. Auf dieser Definition von $g$ aufbauend können wir uns anschliessend überlegen, wie die Matrix $G$ aufgestellt werden kann. Die folgenden Eigenschaften für die genetischen Effekte $g$ und für die GRM $G$ sollen gelten. 

1. Die genetischen Effekte $g$ sollen der Summe aller SNP-Effekte $q$ entsprechen. 
2. Die genetischen Effekte $g$ sollen nicht als Absolute Werte sondern analog zu den Zuchtwerten aus dem BLUP-Tiermodell als Abweichungen von einer festgelegten Basis definiert sein, das heisst der Erwartungswert $E\left[g\right] = 0$. 
3. Wie schon erwähnt soll die Covarianz der genetischen Effekte $g$ dem Produkt aus GRM $G$ und der Varianzkomponente $\sigma_g^2$ entsprechen, d.h. $var(g) = G * \sigma_g^2$.
4. Die GRM $G$ soll ähnlich wie die additive Verwandtschaftsmatrix $A$ aussehen, d.h. die Diagnoalelemente sollen um $1$ liegen und auf der Offdiagonalen sollen hohe Werte mit genetisch ähnlichen Tieren assoziiert werden.

Als Informationsquellen für die Definition von $g$ und zum Aufstellen der GRM $G$ haben wir die SNP-Markerinformationen zur Verfügung. Das hier vorgestellte Material basiert auf den Arbeiten von [@VanRaden2008] und von [@GDHMF2009]. In den folgenden Unterabschnitten wollen wir die Konsequenzen der oben aufgelisteten Eigenschaften analysieren und daraus die GRM $G$ aufstellen.

### Genetische Effekte als Summe der SNP-Effekte
Basierend auf der SNP-Markerinformation können wir Effekte für die einzelnen SNP-Marker schätzen. Wir nehmen hier also an, dass wir den Vektor $q$ kennen. Formell bedeutet die Eigenschaft, dass die genetischen Effekte $g$ als Summe der SNP-Effekte $q$ dargestellte werden können, dass es eine Matrix $U$ gibt, für welche gilt, dass 

\begin{equation}
g = U * q
\label{eq:VecGSumOfVecQ}
\end{equation}
wobei an dieser Stelle die Matrix $U$ noch unbekannt ist. Wir werden diese anhand der nächsten Eigenschaft bestimmten.

### Genetische Effekte als Abweichungen
Die genetischen Effekte sollen, analog zu den Zuchtwerten aus dem BLUP-Tiermodell als Abweichungen von einer festgelegten Basis definiert werden. Die Basis stellt den Nullpunkt der genetischen Effekte dar. Somit kommen die einzelnen Genetischen Effekte $g_i$ für Tier $i$ aus einer Verteilung mit Erwartungswert $E\left[g_i\right] = 0$. Die Frage ist nun, wie muss die Matrix $U$ aussehen, dass unabhängig vom Vektor $q$ der Erwartungswert der Komponenten von $g_i$ gleich null ist.

Betrachten wir die Zufallsvariable $w$ mit den SNP-Genotypencodes in Matrix $W$ im RR-BLUP-Modell (\ref{eq:RRBlupModel}) und nehmen wir an, das Hardy-Weinberg-Gleichgewicht gelte für alle SNP-Genorte, dann sind folgende Realisierungswerte für $w$ möglich

\begin{equation}
w = \left\{ \begin{array}{lll}
0  &  \text{mit Wahrscheinlichkeit} & (1-p)^2\\
1  &  \text{mit Wahrscheinlichkeit} & 2p(1-p) \\
2  &  \text{mit Wahrscheinlichkeit} & p^2
\end{array}
\right.
\label{eq:RandVarGenotypesW}
\end{equation}

Der Erwartungswert der Zufallsvariablen $w$ entspricht

\begin{equation}
E\left[w\right] = 0*(1-p)^2 + 1 * 2p(1-p) + 2 * p^2 = 2p
\label{eq:ExpectedValueW}
\end{equation}

Die Matrix $U$ aus \ref{eq:VecGSumOfVecQ} berechnen wir als Differenz zwischen den Matrizen $W$ und $P$. Die Matrix $P$ besteht aus Kolonnenvektoren $1_n2p_j$ der Länge $n$ für die entsprechenden SNPs $j = 1,\ldots ,m$. Für einen bestimmten SNP-Locus $j$ folgen aufgrund der Definition der Matrix $U$ die folgenden Codierungen der SNP-Genotypen. Dabei nehme wir an, dass das Allel $(G_{2})_j$ mit Frequenz $p_j$ auftritt und das Allel mit der positiven Wirkung ist.

\vspace{2ex}
\begin{center}
\begin{tabular}{|l|l|l|}
\hline
Genotypen     &  Wert            &  Codierung \\
\hline
$(G_1G_1)_j$  &  $-2p_jq_j$      &  $-2p_j$\\
$(G_1G_2)_j$  &  $(1-2p_j)q_j$   &  $1-2p_j$\\
$(G_2G_2)_j$  &  $(2-2p_j)q_j$   &  $2-2p_j$\\
\hline
\end{tabular}
\end{center}

\vspace{2ex}
Unter der Annahme des Hardy-Weinberg-Gleichgewichts für die Genotypen am SNP-Locus $j$ können wir den Erwartungswert für den genetischen Effekt $g$ am SNP-Locus $j$ berechnen. Der Erwartungswert wird über alle Komponenten des Vektors $g$ der genetischen Effekte berechnet.

\begin{equation}
\begin{split}
E\left[g\right]_j & = \left[(1-p_j)^2(-2p_j) + 2p_j(1-p_j)(1-2p_j) + p_j^2(2-2p_j)\right]q_j\\
  & = \left[(1 - 2p_j + p_j^2)(-2p_j) + (2p_j - 2p_j^2)(1-2p_j) + p_j^2(2-2p_j)\right]q_j\\
  & = \left[-2p_j + 4p_j^2 - 2p_j^3 + 2p_j - 4p_j^2 - 2p_j^2 + 4p_j^3 + 2p_j^2 - 2p_j^3\right]q_j\\
  & = 0
\end{split}
\label{eq:ExpectedValueGj}
\end{equation}

Die gleiche Herleitung lässt sich für jeden SNP Locus $j = 1,\ldots, m$ machen. Somit ist der Erwartungswert über alle genetischen Komponenten $g_i$ gleich null, unabhängig von den SNP-Effekten $q_j$ am Locus $j$. Somit haben wir die Matrix $U$, welche aus den SNP-Effekten $q$ in \ref{eq:RRBlupModel} die genetischen Effekte $g$ in \ref{eq:GblupModel} berechnet, gefunden.

### Alternative Codierung
Anstelle der verwendeten Codierungen von $0$, $1$ und $2$ für die SNP-Genotypen können diese auch mit $-1$, $0$ und $1$ codiert werden. Diese Codierung wird in [@VanRaden2008] zum Aufstellen der GRM $G$ verwendet. Auch im Paper von [@GDHMF2009] wird diese Codierung verwendet. Am prinzipiellen Vorgehen ändert sich aber dadurch nicht. Nur die verwendeten Werte in den Matrizen sind anders. Die Matrix $W$ unter der alternativen Codierung besteht nun aus Werten $-1$, $0$ und $1$. Die Zufallsvariable $w$, welche wir in \ref{eq:RandVarGenotypesW} definiert zur Bestimmung der Matrix $P$ verwendet hatten, sieht unter der alternativen Codierung wie folgt aus.

\begin{equation}
w = \left\{ \begin{array}{lll}
-1  &  \text{mit Wahrscheinlichkeit} & (1-p)^2\\
0  &  \text{mit Wahrscheinlichkeit} & 2p(1-p) \\
1  &  \text{mit Wahrscheinlichkeit} & p^2
\end{array}
\right.
\label{eq:RandVarGenotypesWalternative}
\end{equation}

Der Erwartungswert für $w$ unter der alternativen Codierung ist dann

\begin{equation}
E\left[w\right] = (-1)*(1-p)^2 + 0 * 2p(1-p) + 1 * p^2 = -1 + 2p - p^2 + p^2 = 2p - 1 = 2(p - 0.5)
\label{eq:ExpectedValueWalternative}
\end{equation}


Die Matrix $U$ (welche der Matrix $Z$ in [@VanRaden2008] entspricht) kann nun wie folgt aufgestellt werden. Die SNP-Genotypen werden in der Matrix $M$ mit den Werten $-1$, $0$ und $1$ kodiert. Die Matrix $P$ enthält in jeder Kolonne $j$ zweimal die Differenz zwischen der Frequenz des raren Allels minus $0.5$. Die Matrix $U$ wird als Differenz $U = M - P$ berechnet. Die Matrix $P$ enthält in jeder Kolonne $j$ zweimal die Differenz zwischen der Frequenz des raren Allels minus $0.5$. 

### Varianz der genetischen Effekte
Aufgrund der postulierten Eigenschaften soll die Varianz $var(g)$ der genetischen Effekte berechnet werden als das Produkt der GRM $G$ mal die gemeinsame Varianzkomponente $\sigma_g^2$. Formell entspricht das $var(g) = G * \sigma_g^2$. 

Aus der Theorie folgt unter Berücksichtigung von (\ref{eq:VecGSumOfVecQ}), dass $var(g) = U * var(q) * U^T$ ist. Für die Varianz der SNP-Effekte nehmen wir an, dass $var(q) = I\sigma_q^2$. Dies bedeutet, dass die Kovarianz der genetischen Effekte $g$ vereinfacht zu $var(g) = UU^T \sigma_q^2$. 

Im Paper von [@GDHMF2009] wurde $\sigma_g^2$ aus $\sigma_q^2$ hergeleitet. Die resultierende Formel sieht wie folgt aus.

\begin{equation}
\sigma_g^2 = 2 \sum_j^m p_j(1-p_j) \sigma_q^2
\label{eq:GenomicVariance}
\end{equation}

Fassen wir alle diese Beziehungen zusammen, können wir die verschiedenen Ausdrücke für die Kovarianz der genetischen Effekte gleichsetzen. 

\begin{equation}
var(g) = G * \sigma_g^2 = UU^T \sigma_q^2
\label{eq:GenomicVarianceTwoExpr}
\end{equation}

Ersetzen wir $\sigma_g^2$ in (\ref{eq:GenomicVarianceTwoExpr}) durch den Ausdruck in (\ref{eq:GenomicVariance}) so folgt

\begin{equation}
G * 2 \sum_j^m p_j(1-p_j) \sigma_q^2 = UU^T \sigma_q^2
\label{eq:GenomicVarianceInserted}
\end{equation}

Aus der Gleichung in (\ref{eq:GenomicVarianceInserted}) kann die genomische Verwandtschaftsmatrix $G$ berechnet werden als

\begin{equation}
G = \frac{UU^T}{2\sum_j p_j(1-p_j)}
\label{eq:GenomRelMat}
\end{equation}
